import unittest
from springdroid import SpringDroid

class SpringDroidTest(unittest.TestCase):
    def test_springdroid_program(self):
        droid = SpringDroid("input.txt")
        output = droid.run_script("NOT D J\nWALK\n")
        expected = \
"""Didn't make it across:

.................
.................
@................
#####.###########

.................
.................
.@...............
#####.###########

.................
..@..............
.................
#####.###########

...@.............
.................
.................
#####.###########

.................
....@............
.................
#####.###########

.................
.................
.....@...........
#####.###########

.................
.................
.................
#####@###########

"""
        self.assertEqual("".join(output), expected)

if __name__ == '__main__':
    unittest.main()


